### ISSUE TITLE
Beware, this repo is a scam.

### ISSUE THREAD

**Issue by gogabidzia** [liamprodev/Chainfuse-Web3-Hiring#1]

**Comment by liamprodev** [comment]
As a programmer expert, it is essential to possess the necessary skills and attention to detail to ensure the highest level of security in our projects. Our CTO has emphasized the utmost importance of this aspect.

As I said in test channel, @gogabidzia should dm me with sensitive question. btw you are chosen one of powerful candidates... Good Job

**Comment by liamprodev** [comment]
closed
